-- Persistir imágenes en Postgres (local + Render + Supabase)

create table if not exists public.stored_media (
  id bigint generated by default as identity primary key,
  public_id varchar(64) not null,
  content_type varchar(100) not null,
  data bytea not null,
  created_at timestamptz not null default now()
);

create unique index if not exists ix_stored_media_public_id on public.stored_media (public_id);
create index if not exists ix_stored_media_id on public.stored_media (id);
