-- Server-side notification mailbox (Fase 8)

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users (id) on delete cascade,
  actor_id bigint null references public.users (id) on delete set null,
  type varchar(40) not null,
  entity_type varchar(40) null,
  entity_id bigint null,
  payload jsonb null,
  read_at timestamptz null,
  created_at timestamptz not null default now()
);

create index if not exists ix_notifications_user_id on public.notifications (user_id);
create index if not exists ix_notifications_actor_id on public.notifications (actor_id);
create index if not exists ix_notifications_type on public.notifications (type);
create index if not exists ix_notifications_created_at on public.notifications (created_at);
create index if not exists ix_notifications_user_unread
  on public.notifications (user_id)
  where read_at is null;
