-- Share/report + gamification

alter table public.users
  add column if not exists xp integer not null default 0;

alter table public.users
  add column if not exists level integer not null default 1;

create table if not exists public.post_shares (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users (id) on delete cascade,
  post_id bigint not null references public.posts (id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint uq_user_post_share unique (user_id, post_id)
);

create index if not exists ix_post_shares_user_id on public.post_shares (user_id);
create index if not exists ix_post_shares_post_id on public.post_shares (post_id);

create table if not exists public.post_reports (
  id bigint generated by default as identity primary key,
  reporter_id bigint not null references public.users (id) on delete cascade,
  post_id bigint not null references public.posts (id) on delete cascade,
  reason varchar(280) not null,
  status varchar(20) not null default 'open',
  created_at timestamptz not null default now(),
  constraint uq_user_post_report unique (reporter_id, post_id)
);

create index if not exists ix_post_reports_reporter_id on public.post_reports (reporter_id);
create index if not exists ix_post_reports_post_id on public.post_reports (post_id);

create table if not exists public.badges (
  id bigint generated by default as identity primary key,
  code varchar(40) not null unique,
  name varchar(80) not null,
  description text null,
  icon varchar(40) null
);

create table if not exists public.user_badges (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users (id) on delete cascade,
  badge_id bigint not null references public.badges (id) on delete cascade,
  earned_at timestamptz not null default now(),
  constraint uq_user_badge unique (user_id, badge_id)
);

create index if not exists ix_user_badges_user_id on public.user_badges (user_id);
create index if not exists ix_user_badges_badge_id on public.user_badges (badge_id);

create table if not exists public.xp_events (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users (id) on delete cascade,
  action varchar(40) not null,
  points integer not null,
  created_at timestamptz not null default now()
);

create index if not exists ix_xp_events_user_id on public.xp_events (user_id);
create index if not exists ix_xp_events_action on public.xp_events (action);
