-- Campus events + RSVP

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  creator_id bigint not null references public.users (id) on delete cascade,
  community_id bigint null references public.communities (id) on delete set null,
  title varchar(200) not null,
  description text null,
  starts_at timestamptz not null,
  ends_at timestamptz null,
  location varchar(200) null,
  created_at timestamptz not null default now()
);

create index if not exists ix_events_creator_id on public.events (creator_id);
create index if not exists ix_events_community_id on public.events (community_id);
create index if not exists ix_events_starts_at on public.events (starts_at);

create table if not exists public.event_attendees (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events (id) on delete cascade,
  user_id bigint not null references public.users (id) on delete cascade,
  status varchar(20) not null default 'going',
  created_at timestamptz not null default now(),
  constraint uq_event_user unique (event_id, user_id)
);

create index if not exists ix_event_attendees_event_id on public.event_attendees (event_id);
create index if not exists ix_event_attendees_user_id on public.event_attendees (user_id);
