-- 1:1 messaging

alter table public.users
  add column if not exists last_seen_at timestamptz null;

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  pair_key varchar(40) not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_conversations_pair_key on public.conversations (pair_key);
create index if not exists ix_conversations_updated_at on public.conversations (updated_at);

create table if not exists public.conversation_participants (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations (id) on delete cascade,
  user_id bigint not null references public.users (id) on delete cascade,
  last_read_at timestamptz null,
  created_at timestamptz not null default now(),
  constraint uq_conversation_user unique (conversation_id, user_id)
);

create index if not exists ix_conversation_participants_conversation_id
  on public.conversation_participants (conversation_id);
create index if not exists ix_conversation_participants_user_id
  on public.conversation_participants (user_id);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations (id) on delete cascade,
  sender_id bigint not null references public.users (id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  edited_at timestamptz null
);

create index if not exists ix_messages_conversation_id on public.messages (conversation_id);
create index if not exists ix_messages_sender_id on public.messages (sender_id);
create index if not exists ix_messages_created_at on public.messages (created_at);
