-- Studious Party schema (matches FastAPI SQLAlchemy models)

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username varchar(50) not null,
  email varchar(255) not null,
  password_hash varchar(255) not null,
  avatar_url varchar(500),
  bio text,
  created_at timestamptz not null default now()
);

create unique index if not exists ix_users_username on public.users (username);
create unique index if not exists ix_users_email on public.users (email);
create index if not exists ix_users_id on public.users (id);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  content text not null,
  image_url varchar(500),
  author_id bigint not null references public.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists ix_posts_id on public.posts (id);
create index if not exists ix_posts_author_id on public.posts (author_id);

create table if not exists public.likes (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users (id) on delete cascade,
  post_id bigint not null references public.posts (id) on delete cascade,
  constraint uq_user_post_like unique (user_id, post_id)
);

create index if not exists ix_likes_id on public.likes (id);
create index if not exists ix_likes_user_id on public.likes (user_id);
create index if not exists ix_likes_post_id on public.likes (post_id);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  content text not null,
  user_id bigint not null references public.users (id) on delete cascade,
  post_id bigint not null references public.posts (id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists ix_comments_id on public.comments (id);
create index if not exists ix_comments_user_id on public.comments (user_id);
create index if not exists ix_comments_post_id on public.comments (post_id);
