-- Saves and hashtags for feed social features

create table if not exists public.post_saves (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users (id) on delete cascade,
  post_id bigint not null references public.posts (id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint uq_user_post_save unique (user_id, post_id)
);

create index if not exists ix_post_saves_user_id on public.post_saves (user_id);
create index if not exists ix_post_saves_post_id on public.post_saves (post_id);

create table if not exists public.hashtags (
  id bigint generated by default as identity primary key,
  name varchar(50) not null unique
);

create index if not exists ix_hashtags_name on public.hashtags (name);

create table if not exists public.post_hashtags (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts (id) on delete cascade,
  hashtag_id bigint not null references public.hashtags (id) on delete cascade,
  constraint uq_post_hashtag unique (post_id, hashtag_id)
);

create index if not exists ix_post_hashtags_post_id on public.post_hashtags (post_id);
create index if not exists ix_post_hashtags_hashtag_id on public.post_hashtags (hashtag_id);
