-- Academic resources library

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  name varchar(120) not null unique,
  code varchar(40) null
);

create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  uploader_id bigint not null references public.users (id) on delete cascade,
  subject_id bigint null references public.subjects (id) on delete set null,
  title varchar(200) not null,
  description text null,
  category varchar(40) not null default 'notes',
  file_url varchar(500) not null,
  file_type varchar(100) not null,
  size_bytes bigint not null default 0,
  downloads_count integer not null default 0,
  avg_rating double precision not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists ix_resources_uploader_id on public.resources (uploader_id);
create index if not exists ix_resources_subject_id on public.resources (subject_id);
create index if not exists ix_resources_category on public.resources (category);

create table if not exists public.resource_ratings (
  id bigint generated by default as identity primary key,
  resource_id bigint not null references public.resources (id) on delete cascade,
  user_id bigint not null references public.users (id) on delete cascade,
  score integer not null check (score >= 1 and score <= 5),
  created_at timestamptz not null default now(),
  constraint uq_resource_user_rating unique (resource_id, user_id)
);

create index if not exists ix_resource_ratings_resource_id on public.resource_ratings (resource_id);
create index if not exists ix_resource_ratings_user_id on public.resource_ratings (user_id);
