-- Communities + membership + posts.community_id

create table if not exists public.communities (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  slug varchar(80) not null unique,
  description text null,
  cover_url varchar(500) null,
  rules text null,
  owner_id bigint not null references public.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists ix_communities_slug on public.communities (slug);
create index if not exists ix_communities_owner_id on public.communities (owner_id);

create table if not exists public.community_members (
  id bigint generated by default as identity primary key,
  community_id bigint not null references public.communities (id) on delete cascade,
  user_id bigint not null references public.users (id) on delete cascade,
  role varchar(20) not null default 'member',
  joined_at timestamptz not null default now(),
  constraint uq_community_user unique (community_id, user_id)
);

create index if not exists ix_community_members_community_id on public.community_members (community_id);
create index if not exists ix_community_members_user_id on public.community_members (user_id);

alter table public.posts
  add column if not exists community_id bigint null references public.communities (id) on delete set null;

create index if not exists ix_posts_community_id on public.posts (community_id);
