-- Follow system: users can follow other users

create table if not exists public.follows (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users (id) on delete cascade,
  followed_id bigint not null references public.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint uq_user_followed unique (user_id, followed_id)
);

create index if not exists ix_follows_id on public.follows (id);
create index if not exists ix_follows_user_id on public.follows (user_id);
create index if not exists ix_follows_followed_id on public.follows (followed_id);
